version: "3"
services:
  database:
    image: mongo
    volumes:
      - ./database:/data/db
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - "database"
  frontend:
    build: ./frontend
    ports:
      - "3001:8080"
